version: "3.9"
services:
  chatgpt-next-web:
    profiles: [ "no-proxy" ]
    container_name: chatgpt-next-web
    image: Turker2358/chatgpt-next-web
    ports:
      - 3000:3000
    environment:
      - OPENAI_API_KEY= Empty
      - GOOGLE_API_KEY=Empty
      - CODE=Empty
      - BASE_URL=Empty
      - OPENAI_ORG_ID=Empty
      - HIDE_USER_API_KEY=Empty
      - DISABLE_GPT4=Empty
      - ENABLE_BALANCE_QUERY=Empty
      - DISABLE_FAST_LINK=Empty
      - OPENAI_SB=Empty

  chatgpt-next-web-proxy:
    profiles: [ "proxy" ]
    container_name: chatgpt-next-web-proxy
    image: Turker2358/chatgpt-next-web
    ports:
      - 3000:3000
    environment:
      - OPENAI_API_KEY=Empty
      - GOOGLE_API_KEY=Empty
      - CODE=Empty
      - PROXY_URL=Empty
      - BASE_URL=Empty
      - OPENAI_ORG_ID=Empty
      - HIDE_USER_API_KEY=Empty
      - DISABLE_GPT4=Empty
      - ENABLE_BALANCE_QUERY=Empty
      - DISABLE_FAST_LINK=Empty
      - OPENAI_SB=Empty
